# Generated by Django 4.1.7 on 2023-03-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, upload_to='pokemons'),
        ),
    ]
