# Generated by Django 4.1.7 on 2023-03-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_rename_defence_pokemonentity_sefence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Health',
            new_name='defence',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='sefence',
            new_name='health',
        ),
    ]
